---
- name: Настройка Nginx с несколькими виртуальными хостами
  hosts: all
  become: yes
  vars:
    vhosts:
      - name: nginx1.devops.situ
        port: 80
      - name: nginx2.devops.situ
        port: 8080

  roles:
    - role: nginx_vhost
